run:
  timeout: 5m
  tests: true


linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - bodyclose
    - unparam

  disable:
    - lll
    - funlen
    - goconst
    - cyclop

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
